import type { Metadata } from 'next'
import {Nunito_Sans } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import Script from 'next/script'
import {Providers} from "./providers";

const font = Nunito_Sans({ subsets: ['latin'] })


  
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head><link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css" rel="stylesheet" /></Head>
      <body className={font.className}>
        <Providers>
          {children}
        </Providers>
      </body>
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js" />

    </html>
  )
}
